### Generacion de noticias

In [1]:
import pandas as pd
import numpy as np
#import transformers
#from transformers import pipeline
#transformers.__version__

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv("dataEtiquetada.csv")
df.drop(columns=['media_outlet','url','title','content', 'topic'], inplace=True)
print(len(df))
display(df['label'].value_counts())

42463

mundo                         9957
deporte                       9705
política y conflictos         6422
ciencia y tecnología          5689
crimen, delitos y justicia    2740
salud                         2698
economía                      2279
catástrofes y accidentes      1815
ecología y planeta             643
cultura y arte                 515
Name: label, dtype: int64

In [4]:
df3 = df.loc[df['label']=="ciencia y tecnología"] #tope

df1 = df.loc[df['label']=="economía"]
df4 = df.loc[df['label']=="catástrofes y accidentes"]
df5 = df.loc[df['label']=="cultura y arte"]
df7 = df.loc[df['label']=="ecología y planeta"]
df8 = df.loc[df['label']=="crimen, delitos y justicia"]
df9 = df.loc[df['label']=="salud"]

In [5]:
display(df7.head(4), df5.head(4),df4.head(4) )

                                                  text               label
128  Warren Buffett es considerado uno de los más g...  ecología y planeta
148  Carabineros detuvo a 17 personas que participa...  ecología y planeta
239  Desde que los cientos de países del mundo impu...  ecología y planeta
240  La mañana de este martes, las autoridades arge...  ecología y planeta

                                                  text           label
361  PlayStation anunció los videojuegos más descar...  cultura y arte
362  Ayaan Moosa y Mikaeel Ishaa, de seis años, dec...  cultura y arte
574  Hace unos días, cuando se anunció la suspensió...  cultura y arte
684  Durante la madrugada de este martes, el cadáve...  cultura y arte

,text,label
33024,Durante la tarde de este martes se registró un...,catástrofes y accidentes
33031,Un nuevo temblor se registró a las 6:31 horas ...,catástrofes y accidentes
33032,"La madrugada de este martes 01 de septiembre, ...",catástrofes y accidentes
33033,Durante la madrugada de este martes 01 de sept...,catástrofes y accidentes

#### 1. Generación de noticias categoría *7.ecología y planeta*

In [6]:
import random 
togen = len(df3) - len(df7)
text = df7[['text']]
#text_generator = pipeline("text-generation", model="DeepESP/gpt2-spanish", tokenizer="DeepESP/gpt2-spanish")
generated_cat7 = []

for i in range(togen):
    string1 = str(text.values[random.randint(0, len(df7)-1)]).strip("['']")[0:random.randint(0,len(text))]
    string2 = str(text.values[random.randint(0, len(df7)-1)]).strip("['']")[0:random.randint(0,len(text))]
    string3 = str(text.values[random.randint(0, len(df7)-1)]).strip("['']")[0:random.randint(0,len(text))]
    res = string1 + string2 + string3
    generated_cat7.append(res)
    #generated_cat7.append(text_generator(res, max_length=100, do_sample=False))

In [7]:
cat7 = pd.DataFrame(generated_cat7,  columns = ['text'])
cat7['label']= "ecología y planeta"

In [8]:
cat7

                                                   text               label
0     Se ha visto mucha reacción sobre la reunión ef...  ecología y planeta
1     El gobierno de Japón planea lanzar al Océano P...  ecología y planeta
2     Este martes el ministro de HacienLlegó el día ...  ecología y planeta
3     Para conocer en detalle el trabajo de una Alia...  ecología y planeta
4     Durante la noche de este lunes, un incendio af...  ecología y planeta
...                                                 ...                 ...
5041  Cuando resta sólo una semana para el final del...  ecología y planeta
5042  El Ministerio de Salud publicó este sábado 19 ...  ecología y planeta
5043  Este año hubo tantas tormentas tropicales en e...  ecología y planeta
5044   Carabineros informó que este sábado entregó 1...  ecología y planeta
5045  En medio de la oscuridad de la noche y de vari...  ecología y planeta

[5046 rows x 2 columns]

#### Generacion de noticias categoria _5. cultura y arte_

In [9]:
togen = len(df3) - len(df5)
text = df5[['text']]
#text_generator = pipeline("text-generation", model="DeepESP/gpt2-spanish", tokenizer="DeepESP/gpt2-spanish")
generated_cat5 = []

for i in range(togen):
    string1 = str(text.values[random.randint(0, len(df5)-1)]).strip("['']")[0:random.randint(0,len(text))]
    string2 = str(text.values[random.randint(0, len(df5)-1)]).strip("['']")[0:random.randint(0,len(text))]
    string3 = str(text.values[random.randint(0, len(df5)-1)]).strip("['']")[0:random.randint(0,len(text))]
    res = string1 + string2 + string3
    generated_cat5.append(res)
    #generated_cat7.append(text_generator(res, max_length=100, do_sample=False))

In [10]:
cat5 = pd.DataFrame(generated_cat5,  columns = ['text'])
cat5['label']= "cultura y arte"

In [11]:
cat5

                                                   text           label
0     Colo Colo tuvo un primer tiempo para el olvido...  cultura y arte
1     La modelo venezolana Sharon Fonseca, novia del...  cultura y arte
2     Una escalofDonald Trump oficializó este miérco...  cultura y arte
3     El pasado martes 27 de octubre El Ciudadano\xa...  cultura y arte
4     Carnaval del Sur invita a toda la comunidad a ...  cultura y arte
...                                                 ...             ...
5169  Aunque se suponía que tenía un contrato firmad...  cultura y arte
5170  El Ministerio de Salud publicó este sábado 7 d...  cultura y arte
5171  La cantante chilena Mon Laferte consiguió un n...  cultura y arte
5172  Este domingo tendremos una nueva edición de "E...  cultura y arte
5173  ¿Qué entendemos por derechos humanos? ¿Qué ari...  cultura y arte

[5174 rows x 2 columns]

#### Generacion de noticias categoria _4. catástrofes y accidentes_

In [12]:
togen = len(df3) - len(df4)
text = df4[['text']]
#text_generator = pipeline("text-generation", model="DeepESP/gpt2-spanish", tokenizer="DeepESP/gpt2-spanish")
generated_cat4 = []

for i in range(togen):
    string1 = str(text.values[random.randint(0, len(df4)-1)]).strip("['']")[0:random.randint(0,len(text))]
    string2 = str(text.values[random.randint(0, len(df4)-1)]).strip("['']")[0:random.randint(0,len(text))]
    string3 = str(text.values[random.randint(0, len(df4)-1)]).strip("['']")[0:random.randint(0,len(text))]
    res = string1 + string2 + string3
    generated_cat4.append(res)
    #generated_cat7.append(text_generator(res, max_length=100, do_sample=False))

In [13]:
cat4 = pd.DataFrame(generated_cat4,  columns = ['text'])
cat4['label']= "catástrofes y accidentes"

In [14]:
cat4

,text,label
0,Esta noche la Oficina Nacional de Emergencia (...,catástrofes y accidentes
1,La tarde de este miércoles se registró un movi...,catástrofes y accidentes
2,A casi cuatro años del hallazgo del cuerpo de ...,catástrofes y accidentes
3,"El ministro (s) del Interior, Juan Francisco G...",catástrofes y accidentes
4,"El ministro de Defensa, Mario Desbordes, se re...",catástrofes y accidentes
...,...,...
3869,"""Un\xa0temblor\xa0se registró a las 14:32 hora...",catástrofes y accidentes
3870,"Durante la tarde de este jueves, se decretó ""A...",catástrofes y accidentes
3871,Un accidente de tránsito se produjo la tarde d...,catástrofes y accidentes
3872,Carabineros recibió anoche un llamado de que u...,catástrofes y accidentes
3873,Dos trabajadores de una faena forestal termina...,catástrofes y accidentes

#### Generacion de noticias categoria _1. economía_

In [15]:
togen = len(df3) - len(df1)
text = df1[['text']]
#text_generator = pipeline("text-generation", model="DeepESP/gpt2-spanish", tokenizer="DeepESP/gpt2-spanish")
generated_cat1 = []

for i in range(togen):
    string1 = str(text.values[random.randint(0, len(df1)-1)]).strip("['']")[0:random.randint(0,len(text))]
    string2 = str(text.values[random.randint(0, len(df1)-1)]).strip("['']")[0:random.randint(0,len(text))]
    string3 = str(text.values[random.randint(0, len(df1)-1)]).strip("['']")[0:random.randint(0,len(text))]
    res = string1 + string2 + string3
    generated_cat1.append(res)
    #generated_cat7.append(text_generator(res, max_length=100, do_sample=False))

In [16]:
cat1 = pd.DataFrame(generated_cat1,  columns = ['text'])
cat1['label']= "economía"

In [17]:
cat1

                                                   text     label
0     Una querella por maltrato animal presentó la a...  economía
1     El sistema de transporte Red activó un plan de...  economía
2     "Es un reajuste que está por debajo de la expe...  economía
3     El dólar subió nuevamente este miércoles y que...  economía
4     El ministro de Salud,  Enrique Paris,  señaló ...  economía
...                                                 ...       ...
3405  El diputado independiente, Karim Bianchi Retam...  economía
3406  El primer contagiado por covid-19 en Chile era...  economía
3407  La actitud frente al segundo retiro del 10% le...  economía
3408  El ministro de Hacienda, Ignacio Briones, habl...  economía
3409  A horas de que terminara el año legislativo 20...  economía

[3410 rows x 2 columns]

#### Generacion de noticias categoria _8.crimen, delitos y justicia_

In [18]:
togen = len(df3) - len(df8)
text = df8[['text']]
#text_generator = pipeline("text-generation", model="DeepESP/gpt2-spanish", tokenizer="DeepESP/gpt2-spanish")
generated_cat8 = []

for i in range(togen):
    string1 = str(text.values[random.randint(0, len(df8)-1)]).strip("['']")[0:random.randint(0,len(text))]
    string2 = str(text.values[random.randint(0, len(df8)-1)]).strip("['']")[0:random.randint(0,len(text))]
    string3 = str(text.values[random.randint(0, len(df8)-1)]).strip("['']")[0:random.randint(0,len(text))]
    res = string1 + string2 + string3
    generated_cat8.append(res)
    #generated_cat7.append(text_generator(res, max_length=100, do_sample=False))

In [19]:
cat8 = pd.DataFrame(generated_cat8,  columns = ['text'])
cat8['label']= "crimen, delitos y justicia"

In [20]:
cat8

,text,label
0,Una nueva jornada de manifestaciones se desarr...,"crimen, delitos y justicia"
1,Los diputados de la UDI Jorge Alessandri y Ser...,"crimen, delitos y justicia"
2,Un hombre quedó en prisión preventiva luego de...,"crimen, delitos y justicia"
3,El director del Instituto Nacional de Derechos...,"crimen, delitos y justicia"
4,"Durante la noche de este miércoles, un hombre ...","crimen, delitos y justicia"
...,...,...
2944,"El fiscal nacional, Jorge Abbott, reaccionó d...","crimen, delitos y justicia"
2945,"Mario Carrera Guerrero (44), actual fiscal adj...","crimen, delitos y justicia"
2946,"Este miércoles, ocho personas resultaron deten...","crimen, delitos y justicia"
2947,Detectives de la Brigada de Investigación Crim...,"crimen, delitos y justicia"
2948,Luego de que el pasado lunes convocara a un ac...,"crimen, delitos y justicia"

#### Generacion de noticias categoria _9. salud_

In [21]:
togen = len(df3) - len(df9)
text = df9[['text']]
generated_cat9 = []

for i in range(togen):
    string1 = str(text.values[random.randint(0, len(df9)-1)]).strip("['']")[0:random.randint(0,len(text))]
    string2 = str(text.values[random.randint(0, len(df9)-1)]).strip("['']")[0:random.randint(0,len(text))]
    string3 = str(text.values[random.randint(0, len(df9)-1)]).strip("['']")[0:random.randint(0,len(text))]
    res = string1 + string2 + string3
    generated_cat9.append(res)

In [22]:
cat9 = pd.DataFrame(generated_cat9,  columns = ['text'])
cat9['label']= "salud"

In [23]:
cat9

                                                   text  label
0     El ministerio de Salud entregó este miércoles ...  salud
1     Este martes se reanudó de forma semipresencial...  salud
2     El último día de 2020, el ministro de Educació...  salud
3     Siete muertos y 252 casos nuevos de covid-19 r...  salud
4     Pese al llamado de las autoridades para prefer...  salud
...                                                 ...    ...
2986  El ministro de Salud, Enrique Paris, lideró el...  salud
2987  La bolsa de Tokio abrió con una fuerte "El  Mi...  salud
2988  Por primera vez desde que se tiene el registro...  salud
2989   Este martes, el Presidente Sebastián Piñera a...  salud
2990  Este martes, el Ministerio de Salud entregó un...  salud

[2991 rows x 2 columns]

### concatenación de dfs generados

In [25]:
frames = [df, cat7, cat5, cat4, cat1, cat8, cat9]
dataset1 = pd.concat(frames)
display(dataset1['label'].value_counts())

mundo                         9957
deporte                       9705
política y conflictos         6422
ciencia y tecnología          5689
crimen, delitos y justicia    5689
ecología y planeta            5689
catástrofes y accidentes      5689
cultura y arte                5689
salud                         5689
economía                      5689
Name: label, dtype: int64

In [26]:
dataset1.to_csv("dataGenerada.csv", index=False) 
print("Ok")

Ok